export const FETCH_AGENDAS_LIST_REQUEST = 'agenda/FETCH_LIST_REQUEST';

export const FETCH_AGENDAS_LIST_SUCCESS = 'agenda/FETCH_LIST_SUCCESS';

export const FETCH_AGENDAS_LIST_FAILURE = 'agenda/FETCH_LIST_FAILURE';
